//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jiifureit.Dapper.OutsideSql.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Jiifureit.Dapper.OutsideSql.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   No UPDATE list に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EDA00012 {
            get {
                return ResourceManager.GetString("EDA00012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} not closed in ({1}) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EDAO0002 {
            get {
                return ResourceManager.GetString("EDAO0002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ({0}) is not bool expression に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EDAO0003 {
            get {
                return ResourceManager.GetString("EDAO0003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Condition of IF comment not found に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EDAO0004 {
            get {
                return ResourceManager.GetString("EDAO0004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Target for update must be single row(actual:{1}).({0}) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EDAO0005 {
            get {
                return ResourceManager.GetString("EDAO0005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   END comment not found に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EDAO0007 {
            get {
                return ResourceManager.GetString("EDAO0007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The property type is wrong: name=[{0}] type=[{1}] に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EDAO0010 {
            get {
                return ResourceManager.GetString("EDAO0010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SQL file not found. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EDAO0025 {
            get {
                return ResourceManager.GetString("EDAO0025", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Method&apos;s return element type({0}) is not able to assign from result.({1}). に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EDAO0026 {
            get {
                return ResourceManager.GetString("EDAO0026", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CSharpScriptException occured, because {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ESSR0073 {
            get {
                return ResourceManager.GetString("ESSR0073", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Parameter({0}) not found に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WDAO0001 {
            get {
                return ResourceManager.GetString("WDAO0001", resourceCulture);
            }
        }
    }
}
